on:
  push:
    branches:
      - master
      
permissions:
  contents: write
  pull-requests: write
  
name: release-please

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Run release-please to create a new release
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: php

      # 3. Create a ZIP file of the repository
      - name: Create ZIP file
        run: |
          zip -r mod-edusign.zip ./*

      # 4. Upload the ZIP file to the release
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: mod-edusign.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}