on:
  push:
    branches:
      - master
      
permissions:
  contents: write
  pull-requests: write
  
name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: php
  publish-artifacts:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create ZIP file
        run: |
          rm -Rf mod_edusign mod_edusign-${{ needs.release-please.outputs.tag_name }}.zip
          mkdir mod_edusign
          rsync -r --exclude '.git' --exclude '.github' --exclude 'mod_edusign' ./ mod_edusign
          zip -r mod_edusign-${{ needs.release-please.outputs.tag_name }}.zip mod_edusign
      - name: Publish zip file
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: mod_edusign-${{ needs.release-please.outputs.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Send the good news to slack
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "channel": "Une nouvelle version du module Edusign pour Moodle est disponible",
              "blocks":[
                  {
                    "type":"section",
                    "text":{
                        "type":"plain_text",
                        "emoji":true,
                        "text":"Une nouvelle version du module Edusign pour Moodle est disponible"
                    }
                  },
                  {
                    "type":"divider"
                  },
                  {
                    "type":"section",
                    "text":{
                        "type":"mrkdwn",
                        "text":"*<https://github.com/Edusign/moodle-mod_edusign/releases/tag/${{ needs.release-please.outputs.tag_name }}|Release ${{ needs.release-please.outputs.tag_name }}>*\nUn nouvelle release a été crée pour le plugin *mod_edusign* en version *${{ needs.release-please.outputs.tag_name }}*\n<https://github.com/Edusign/moodle-mod_edusign/releases/download/${{ needs.release-please.outputs.tag_name }}/mod_edusign-${{ needs.release-please.outputs.tag_name }}.zip|Cliquez ici> pour télécharger le fichier .zip"
                    },
                    "accessory":{
                        "type":"image",
                        "image_url":"https://info.payara.fish/hubfs/newrelease.png",
                        "alt_text":"calendar thumbnail"
                    }
                  },
                  {
                    "type":"context",
                    "elements":[
                        {
                          "type":"image",
                          "image_url":"https://cdn-glapd.nitrocdn.com/carLIEFHsZWYaqtkCbVAhEibLXEnyTnJ/assets/images/optimized/rev-7fc7c7e/www.top10hebergeurs.com/wp-content/uploads/2022/05/pngwing.com-1.png",
                          "alt_text":"notifications warning icon"
                        },
                        {
                          "type":"mrkdwn",
                          "text":"*Nouvelle version ${{ needs.release-please.outputs.tag_name }} du plugin mod_edusign *"
                        }
                    ]
                  }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK